### ISSUE TITLE
pve之.1-8版本安装提示跳过

### ISSUE THREAD

**Issue by hanlin0323** [awesometic/realtek-r8125-dkms#14]
Module build for kernel 5.13.19-2-pve was skipped since the
kernel headers for this kernel does not seem to be installed.

**Comment by awesometic** [comment]
Hello. Have you installed the kernel header package properly?
I don't know what OS you're using now but in common, in the Debian/Ubuntu OS you can install that by `sudo apt install linux-headers-$(uname -r)`

**Comment by awesometic** [comment]
I will close this issue since it is not activated for about 3 months.
