### ISSUE TITLE
Incorrect make command does extra install

### ISSUE THREAD

**Issue by kalj** [awesometic/realtek-r8125-dkms#15]
I believe this line is not quite right:
https://github.com/awesometic/realtek-r8125-dkms/blob/master/dkms.conf#L5
By having the make target `all` there, the `install` target will be built as well resulting in the `.ko` file being copied a second time, to something like `/usr/lib/modules/5.XX.X-XX-generic/kernel/drivers/net/ethernet/realtek/r8125.ko`. For me this lead to a duplicate detection, resulting in the actual module not being installed, and some secure boot signature issues. I think the correct make target is `modules`, see here for instance:
https://aur.archlinux.org/cgit/aur.git/tree/dkms.conf?h=r8125-dkms#n3
Changing that fixed it for me.

**Comment by awesometic** [comment]
Hello. Thanks for the information. Yeah, seems it should be patched.
After testing in some cases I will patch that part soon.

**Comment by awesometic** [comment]
I made a patch for correcting the mentioned make target.

Thanks again 😄
