### ISSUE TITLE
Can you make a DKMS of r8156b?

### ISSUE THREAD

**Issue by ShCby** [awesometic/realtek-r8125-dkms#18]
Hello, can you please make a DKMS about realtek r8156b USB 2.5Gb network adapter?

**Comment by awesometic** [comment]
Hello.

It'd be also useful for Ubuntu/Debian systems. realtek-r8152-dkms will be presented. 🤔

**Comment by awesometic** [comment]
Hello again.

realtek-r8152-dkms is ready. r8152 module supports the RTL8156 family too.
Can you test this project?
- https://github.com/awesometic/realtek-r8152-dkms

**Comment by ShCby** [comment]
Thank you for your reply.It can be used on r8156b.
