### ISSUE TITLE
hello!   9.010.01 has just been released.  Thankyou for your project!

### ISSUE THREAD

**Issue by barkmann44** [awesometic/realtek-r8125-dkms#27]
hello!   9.010.01 has just been released.  Thankyou for your project!

_Originally posted by @barkmann44 in https://github.com/awesometic/realtek-r8125-dkms/issues/25#issuecomment-1304270361_

**Comment by awesometic** [comment]
Thank you for informing me.

I updated our DKMS package to 9.010.01 :)
