### ISSUE TITLE
hello!   9.010.01 has just been released.  Thankyou for your project!

### ISSUE THREAD

**Issue by LsnmxNB** [awesometic/realtek-r8125-dkms#28]
hello!   9.010.01 has just been released.  Thankyou for your project!

_Originally posted by @barkmann44 in https://github.com/awesometic/realtek-r8125-dkms/issues/25#issuecomment-1304270361_

Please close this thread, it is wrong, thank you

**Comment by awesometic** [comment]
It's okay 😄
