### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by kiplingw** [awesometic/realtek-r8125-dkms#4]
I'd like to take a moment to thank the maintainer for doing a wonderful job in packaging this properly.

**Comment by awesometic** [comment]
Thank you! Really glad to hear that. :smile:

**Comment by ogradyso** [comment]
I agree, finding this repo has made my life so much easier, THANK YOU!

**Comment by PeashyScript** [comment]
I would also like to thank the developer since I have an x490 UNIFY whose ethernet doesn't work on ubuntu 20.04 without this module
