### ISSUE TITLE
9.012.03

### ISSUE THREAD

**Issue by barkmann44** [awesometic/realtek-r8125-dkms#40]
Dear awesometic,  9.012.03 has been released, if you're interested :)  cheers!

**Comment by awesometic** [comment]
Updated :)

- https://github.com/awesometic/realtek-r8125-dkms/commit/b69628224b2bcc0cd7f83232f5be4a41300a80d4
- https://github.com/awesometic/realtek-r8125-dkms/releases/tag/9.012.03-1
