### ISSUE TITLE
2.5G Ethernet LINUX driver r8125 for kernel up to 6.8	9.013.02	2024/04/18

### ISSUE THREAD

**Issue by bigboo3000** [awesometic/realtek-r8125-dkms#53]
Hi,
there is a new updated driver on realtek site
https://www.realtek.com/Download/List?cate_id=584

2.5G Ethernet LINUX driver r8125 for kernel up to 6.8 | 9.013.02 | 2024/04/18

**Comment by awesometic** [comment]
Thank you for notifying me, but it is already applied :)

- https://github.com/awesometic/realtek-r8125-dkms/commit/fc6c4e0dcaafd756524a7926b6bbeb01140c2e38
