### ISSUE TITLE
Wrong driver loaded (r8169 instead of r8125)

### ISSUE THREAD

**Issue by pannal** [awesometic/realtek-r8125-dkms#7]
Hey,

I've read that you've removed the explicit removal of the r8169 driver from the original autorun.sh.

This seems to conflict on my system (20.04.1 LTS, HWE kernel); when both modules are present, my Trendnet R8125 is loaded with the r8169 driver instead of the correct one.

I've now removed it manually, is this intentional behaviour?

**Comment by awesometic** [comment]
Actually, that isn't intended. I thought that the system should load both two drivers at the same time but sounds it is not.
Sorry for the inconvenience. I will edit `autorun.sh` back to the original state by your actual experience. 

For those who read this issue thread: This is not related to the Debian packaging way. :)

**Comment by awesometic** [comment]
I found that it also affects delivering the driver as a DKMS package. If the r8169 driver exists on the system then the r8125 driver will not load properly. I should update my Debian packaging scripts to add some codes to remove the existing legacy driver. Anyway, thank you for the report. :smile:

**Comment by terr72** [comment]
@awesometic I need to run r8169 and r8125 simultaneously, since I have two NICs in my computer: one integrated RTL8168 and an addon-card iwth a RTL8125B chipset. Is this not possible?

**Comment by awesometic** [comment]
@terr72 ,

Sorry for the late reply. How about removing the RTL8125 firmware files from the `/lib/firmware/rtl_nic` directory? Like the `sudo rm -f /lib/firmware/rtl_nic/rtl8125*` command. Then I think the `r8169` module won't load the firmware for the RTL8125 chipset so that it could make the `r8125` module working properly.

Hope this works. 🤔

**Comment by shing-lee** [comment]
@awesometic 

`sudo echo 'alias r8169 off' >> /etc/modprobe.d/dkms.conf`
`sudo echo 'r8125' >> /etc/initramfs-tools/modules`
`sudo update-initramfs -u`

**Comment by shing-lee** [comment]
> @awesometic我需要同时运行 r8169 和 r8125，因为我的计算机中有两个 NIC：一个集成 RTL8168 和一个带有 RTL8125B 芯片组的附加卡。这不可能吗？

sudo echo 'alias r8169 off' >> /etc/modprobe.d/dkms.conf
sudo echo 'r8125' >> /etc/initramfs-tools/modules
sudo update-initramfs -k all -u
sudo reboot
